---
- name: SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive
  tags:
  - prerequisites

- name: Update system
  package:
    name: "*"
    state: latest
  tags:
  - prerequisites

- name: Install common packages
  package:
    name: [emacs-nox,bash-completion,wget,curl,firewalld,python-firewall,yum-utils,lvm2,device-mapper-persistent-data,nfs-utils]
    state: present
  ignore_errors: True
  tags:
  - prerequisites

- name: Disable SWAP
  shell: |
    swapoff -a
  tags:
  - prerequisites

- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'
  tags:
  - prerequisites

- name: Load required network modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack_ipv4
  tags:
  - prerequisites

- name: Adjust sysctl settings
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  ignore_errors: True
  with_items:
    - {key: net.bridge.bridge-nf-call-ip6tables, value: 1}
    - {key: net.bridge.bridge-nf-call-iptables,  value: 1}
    - {key: net.ipv4.ip_forward,  value: 1}
  tags:
  - prerequisites

- name: set local hostname to {{ inventory_hostname }}
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
  - prerequisites
