---
- name: Removing repository definition for k8s
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /etc/yum.repos.d/kubernetes.repo
  - /etc/yum.repos.d/docer-ce.repo
  tags:
  - uninstall


- name: Uninstalling K8S related packages
  yum:
    name: "{{ packages }}"
    state: absent
  tags:
  - uninstall

- name: Removing miscellaneous files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /etc/kubernetes/
  - /var/lib/etcd/
  - $HOME/.kube/
  - /etc/docker
  - /etc/systemd/system/docker.service.d
  - /etc/containerd
  tags:
  - uninstall


