all:
  children:
    cluster:
      children:
        k8smasters:
          hosts:
            pdb-hp-linux-21.rcsb.rutgers.edu: {}
        k8sworkers:
          hosts:
            pdb-hp-linux-39.rcsb.rutgers.edu: {}
            pdb-hp-linux-40.rcsb.rutgers.edu: {}
    ungrouped: {}
