---
#
- name: create join token
  shell: kubeadm token create
  register: token_raw
  delegate_to: "{{ groups['k8smasters'][0] }}"
  tags:
  - install_workers

- debug: var=token_raw.stdout_lines

- name: set token
  set_fact:
    join_token: "{{ token_raw.stdout_lines[0] }}"
  tags:
  - install_workers

- debug: var=join_token

- name: reset worker component
  shell: "kubeadm reset --force"
  register: reset_cluster
  tags:
  - install_workers

- name: join the worker to the k8s cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm join --token {{ join_token }} \
                --discovery-token-unsafe-skip-ca-verification \
                {{ master_ip }}:6443
  register: join_cluster
  tags:
  - install_workers

- debug: var=join_cluster.stdout_lines
