apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-kube-vol
  labels:
    type: local
spec:
  storageClassName: manualnfs
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    server: 128.6.239.34
    path: "/export/RCSB-A/rcsba-dsa1"
