---
- name: Add kubernetes repository
  template:
    src:  k8s.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
  tags:
  - install-packages

- name: Install kubernetes packages
  yum:
    name: [kubelet,kubeadm,kubectl]
    disable_excludes: kubernetes
  tags:
  - install-packages

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  tags:
  - install-packages

